import React, { useEffect } from "react";
import { useSignInWithGoogle } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";
import Head from "next/head";
import { motion } from "framer-motion";
import { useAuthState } from "react-firebase-hooks/auth";

import { auth } from "../../firebase/firebase";

type SignInProps = {};

const SignIn: React.FC<SignInProps> = () => {
  const router = useRouter();
  const [user] = useAuthState(auth);
  const [signInWithGoogle, userCred, loading, error] =
    useSignInWithGoogle(auth);

  const handleSignUp = async () => {
    signInWithGoogle();
  };

  useEffect(() => {
    if (user) {
      router.push("/");
    } else {
      console.log("You Need To Login");
    }
  }, [user, router]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="dark:bg-[#15202b] h-screen overflow-hidden"
    >
      <Head>
        <title>Cardinal&trade;</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cardinal-images.s3.us-west-1.amazonaws.com/titanium_logo-transparent.jpg"
        />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen py-2 -mt-56 px-14 text-center pt-60">
        <img
          style={{ height: "100px" }}
          src="https://cardinal-images.s3.us-west-1.amazonaws.com/titanium_logo-transparent.jpg"
          alt="Logo"
        />
        <p className="font-xs italic">
          Login
        </p>
        <div className="mt-20">
          <div>
            <button
              className="p-3 bg-twitter rounded-lg text-white font-bold hover:bg-gray-500"
              onClick={handleSignUp}
            >
              Sign in with Google
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
export default SignIn;
